spring.application.name=VenueWebAppProject
spring.datasource.url=jdbc:postgresql://localhost:5432/venue_db
spring.datasource.username=venue
spring.datasource.password=venuepass
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
jwt.secret=this-is-a-temporary-development-secret-change-this-later-1234567890
jwt.expiration=86400000