spring.application.name=VenueWebAppProject
spring.datasource.url=jdbc:postgresql://localhost:5432/venue_db
spring.datasource.username=venue
spring.datasource.password=venuepass
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true